name: Build
on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.53.0
          - stable
          - beta
          - nightly 
        target:
          - x86_64-unknown-linux-gnu
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          override: true
      - name: test
        run: |
          cargo test 
      - name: check formatting
        run: cargo fmt -- --check
